runtime:
  ros__parameters:
    # Also selects the detailed RViz config and full Crazyflie URDF.
    mode: "debug"

data_logging:
  ros__parameters:
    csv_dir: "~/hitl_ws/src/flying_pen/bag/logging"
    publish_topic: "/data_logging_msg"
    cf_ns: "/cf2"
    loop_hz: 50.0

data_logging_firmware_debug:
  ros__parameters:
    history_sec: 8.0
    update_hz: 30.0
    render_hz: 15.0
    topic: "/data_logging_msg"
